name: Build and Package pymongo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull Python 3.11 Docker image
      run: docker pull python:3.11

    - name: Create working directory
      run: mkdir -p build

    - name: Run Docker container and install pymongo
      run: |
        docker run --rm -v ${{ github.workspace }}/build:/build python:3.11 /bin/bash -c "
        pip install pymongo -t /build/pymongo_lib
        "

    - name: Create pymongo.zip
      run: |
        cd build/pymongo_lib
        zip -r ../pymongo.zip .
        cd ../

    - name: Add pymongo.zip to repository
      run: |
        mkdir -p ${{ github.workspace }}/library
        mv build/pymongo.zip ${{ github.workspace }}/library/
        
    - name: Commit pymongo.zip to repository
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add library/pymongo.zip
        git commit -m 'Add pymongo.zip'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
